#!/usr/bin/env bash

# Convenience script to run the etherspot binary from built source
#
# ./SAMkenX --network goerli

node --default-specifier-resolution=node ./packages/cli/bin/SAMkenX.js start "$@"
